services:
  fastapi:
    build: 
      context: ..
      dockerfile: GraphRAGDocker/Dockerfile
    container_name: fastapi
    ports:
      - "8001:8001"
    volumes:
      - fastapi_data:/app/assets
    networks:
      - backend
    restart: always
    env_file:
      - ./env/.env.app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8001/api/v1/health"]
      interval: 5s
      retries: 5
      timeout: 3s
      start_period: 5s
  
  streamlit:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    networks:
      - backend
    restart: always
    depends_on:
      fastapi:
        condition: service_healthy

  qdrant:
    image: qdrant/qdrant:v1.15
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend
    restart: always
  
  nginx:
    image: nginx:stable-alpine3.21-perl
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    networks:
      - backend
    restart: always

  # neo4j:
  #   image: neo4j:latest
  #   container_name: neo4j
  #   ports:
  #     - "7474:7474"  # HTTP
  #     - "7687:7687"  # Bolt
  #   networks:
  #     - backend
  #   env_file:
  #     - ./env/.env.neo4j
  #   volumes:
  #     - neo4j_data:/data
  #     - neo4j_logs:/logs
  #     - neo4j_import:/var/lib/neo4j/import
  #     - neo4j_plugins:/plugins
  #   restart: always

  # prometheus:
  #   image: prom/prometheus:v3.7.3
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - prometheus_data:/prometheus
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - backend
  #   restart: always
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/etc/prometheus/console_libraries'
  #     - '--web.console.templates=/etc/prometheus/consoles'
  #     - '--web.enable-lifecycle'
    
  # grafana:
  #   image: grafana/grafana:12.1-ubuntu
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   env_file:
  #     - ./env/.env.grafana
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - backend
  #   restart: always

networks:
  backend:
    driver: bridge
  
volumes:
  fastapi_data:
  qdrant_data:
  # neo4j_data:
  # neo4j_logs:
  # neo4j_import:
  # neo4j_plugins:
  # prometheus_data:
  # grafana_data: